# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\FcmNotificationService:
        arguments:
            $projectId: '%env(FIREBASE_PROJECT_ID)%'
            $credentialsPath: '%kernel.project_dir%/%env(FIREBASE_CREDENTIALS_PATH)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Migrations/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']